Fatal typo in docker-compose.yml for meilisearch container
the blueprint fort he compose contains

    environment:
      - MEILI_NO_ANALYTICS="true"

This should be a boolean, but is formatted as string. 

Leads to: 

error: invalid value '"true"' for '--no-analytics'
  [possible values: true, false]

and breaks the container at startup